### PR TITLE
fix: add folder fallback to prevent app crash

### LINKED ISSUE #130: Crashes on fresh install because of missing folders
The application doesn't seem to create the required files and folders on first launch which causes it to crash.

`[Nest] 23888  - 2024-10-29 12:27:27    WARN Could not get documents path via WinAPI, trying alternate method
[Nest] 23888  - 2024-10-29 12:27:27    WARN Error: Failed to find My Documents folder
pkg/prelude/bootstrap.js:1872
      throw error;
      ^

Error: ENOENT: no such file or directory, mkdir 'C:\Users\daanb\OneDrive\Documenten\FlyByWireSim\'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Object.mkdirSync (node:fs:1394:3)
    at Object.mkdirSync (pkg/prelude/bootstrap.js:1639:33)
    at C:\snapshot\simbridge\node_modules\file-stream-rotator\FileStreamRotator.js:669:24
    at Array.reduce (<anonymous>)
    at mkDirForFile (C:\snapshot\simbridge\node_modules\file-stream-rotator\FileStreamRotator.js:656:27)
    at Object.getStream (C:\snapshot\simbridge\node_modules\file-stream-rotator\FileStreamRotator.js:532:5)
    at new DailyRotateFile (C:\snapshot\simbridge\node_modules\winston-daily-rotate-file\daily-rotate-file.js:80:57)
    at Object.<anonymous> (C:\snapshot\simbridge\dist\config\winston.service.js)
    at Module._compile (pkg/prelude/bootstrap.js:1926:22)
    at Module._extensions..js (node:internal/modules/cjs/loader:1166:10) {
  errno: -4058,
  syscall: 'mkdir',
  code: 'ENOENT',
  path: 'C:\\Users\\daanb\\OneDrive\\Documenten\\FlyByWireSim\\',
  pkg: true
}

Node.js v18.5.0`

### LINKED ISSUE #133: Simbridge will not run
after update the installer Simbridge will not run.
I get a message in the comand window 
Screenshot (109)
Whts to do to get simbridge working?
Many thanks for help 
greetings
Dieter

### LINKED ISSUE #134: simbrigde not started  Could mot find doc path via WinAPI....
### Installer Version

v0.6.1

### Describe the bug

[Nest] 13016  - 2024-11-11 23:06:22    WARN Could not get documents path via WinAPI, trying alternate method
[Nest] 13016  - 2024-11-11 23:06:22    WARN Error: Failed to find My Documents folder

### Expected behavior

clicked on start and the WARN came up

### Steps to reproduce

xx

### References (optional)

xx

### Additional info (optional)

x

### Discord Username (optional)

akwa57

### PR DESCRIPTION
**Pull request by Saschl**
If Windows Controlled Folder access is enabled, it will prevent simbridge from accessing the documents folder and the app will crash. Added a fallback to use the appdata directory, which is not protected by default.

Note: the old workaround via powershell was removed, as the reason for platform-folders to fail was Windows blocking it as well. So it's not needed anymore IMO.

Fixes #134 
Fixes #133
Fixes #130

### CODE REVIEW

**Review by Maximilian-Reuter — APPROVED** [review]

**Review by Shaddowpain — APPROVED** [review]

File: apps/server/src/utilities/pathUtil.ts [hunk 1]
```diff
@@ -1,27 +1,21 @@
...
-    const output = execFileSync('Powershell.exe', ['-Command', `[System.Environment]::GetFolderPath('MyDocuments')`]);
-    const documents = output.toString().trim();
-    if (!documents) {
-      throw new Error('Path is empty');
-    }
-    return path.join(documents, 'FlyByWireSim', 'Simbridge');
+    return path.join(getPath('appdata'), 'FlyByWireSim', 'Simbridge');
   } catch (e) {
-    Logger.warn('Could not get documents path via Powershell, trying to use %USERPROFILE% method', e);
+    Logger.warn('Could not get AppData path via WinAPI. Giving up.', e);
```
Comment (alepouna) [inline apps/server/src/utilities/pathUtil.ts:17]: I would recommend escalating this to an error rather than a warning.

File: apps/server/src/utilities/pathUtil.ts [hunk 2]
```diff
@@ -1,27 +1,21 @@
...
-import { homedir } from 'os';
-import { execFileSync } from 'child_process';
 
 export const getSimbridgeDir = () => {
   try {
     return path.join(getPath('documents'), 'FlyByWireSim', 'Simbridge');
   } catch (e) {
-    Logger.warn('Could not get documents path via WinAPI, trying alternate method', e);
+    Logger.warn(
+      'Could not get documents path via WinAPI, Windows Controlled Folder Access is likely blocking the app. Using AppData as fallback',
```
Comment (alepouna) [inline apps/server/src/utilities/pathUtil.ts:10]: Could we note here a documentation link to either MS or our docs for how to override WCFA if someone wants to do this? Note as a comment on the code, not the log message FYI.

**Review by alepouna — APPROVED** [review]
Some comments, otherwise LGTM

File: apps/server/src/utilities/pathUtil.ts (hunk 1 above)
Comment (Saschl) [reply apps/server/src/utilities/pathUtil.ts]: Changed 👍

File: apps/server/src/utilities/pathUtil.ts (hunk 2 above)
Comment (Saschl) [reply apps/server/src/utilities/pathUtil.ts:10]: Also the console closes by default so only who either disabled the setting or opens it manually will see the error message. Bot command sounds fine to me
